// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailLink = `-- name: CreateEmailLink :one

INSERT INTO email_links (token_hash, kind, email, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token_hash, kind, email, created_at, expires_at, used_at, superseded_at
`

type CreateEmailLinkParams struct {
	TokenHash []byte             `json:"token_hash"`
	Kind      string             `json:"kind"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Account access: the links sent by email, and requests from people who were
// not invited. See migrations/00009 for why each column exists.
func (q *Queries) CreateEmailLink(ctx context.Context, arg CreateEmailLinkParams) (EmailLink, error) {
	row := q.db.QueryRow(ctx, createEmailLink,
		arg.TokenHash,
		arg.Kind,
		arg.Email,
		arg.ExpiresAt,
	)
	var i EmailLink
	err := row.Scan(
		&i.TokenHash,
		&i.Kind,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.SupersededAt,
	)
	return i, err
}

const deleteAccessRequest = `-- name: DeleteAccessRequest :exec
DELETE FROM access_requests WHERE email = $1
`

// An address that has since been approved and has created its account is no
// longer waiting.
func (q *Queries) DeleteAccessRequest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteAccessRequest, email)
	return err
}

const deleteDeadEmailLinks = `-- name: DeleteDeadEmailLinks :execrows
DELETE FROM email_links WHERE expires_at < now() - interval '7 days'
`

// Links nobody can use any more, kept for a week so a late click still gets the
// honest "expired" rather than looking like a link that never existed.
func (q *Queries) DeleteDeadEmailLinks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadEmailLinks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailLink = `-- name: GetEmailLink :one
SELECT token_hash, kind, email, created_at, expires_at, used_at, superseded_at FROM email_links WHERE token_hash = $1 AND kind = $2
`

type GetEmailLinkParams struct {
	TokenHash []byte `json:"token_hash"`
	Kind      string `json:"kind"`
}

func (q *Queries) GetEmailLink(ctx context.Context, arg GetEmailLinkParams) (EmailLink, error) {
	row := q.db.QueryRow(ctx, getEmailLink, arg.TokenHash, arg.Kind)
	var i EmailLink
	err := row.Scan(
		&i.TokenHash,
		&i.Kind,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.SupersededAt,
	)
	return i, err
}

const recordAccessRequest = `-- name: RecordAccessRequest :one
INSERT INTO access_requests (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE
SET last_requested_at = now(),
    times_requested   = access_requests.times_requested + 1
RETURNING email, first_requested_at, last_requested_at, times_requested
`

// Recording a request. times_requested = 1 in the result means this is the
// first, which is the only time the owner is emailed about it.
func (q *Queries) RecordAccessRequest(ctx context.Context, email string) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, recordAccessRequest, email)
	var i AccessRequest
	err := row.Scan(
		&i.Email,
		&i.FirstRequestedAt,
		&i.LastRequestedAt,
		&i.TimesRequested,
	)
	return i, err
}

const supersedeEmailLinks = `-- name: SupersedeEmailLinks :exec
UPDATE email_links
SET superseded_at = now()
WHERE email = $1 AND kind = $2 AND used_at IS NULL AND superseded_at IS NULL
`

type SupersedeEmailLinksParams struct {
	Email string `json:"email"`
	Kind  string `json:"kind"`
}

// Only the newest link for an address works. Run in the same transaction as
// the insert of the new one, so there is never a moment with two live links or
// with none.
func (q *Queries) SupersedeEmailLinks(ctx context.Context, arg SupersedeEmailLinksParams) error {
	_, err := q.db.Exec(ctx, supersedeEmailLinks, arg.Email, arg.Kind)
	return err
}

const useEmailLink = `-- name: UseEmailLink :one
UPDATE email_links
SET used_at = now()
WHERE token_hash = $1
  AND kind = $2
  AND used_at IS NULL
  AND superseded_at IS NULL
  AND expires_at > now()
RETURNING token_hash, kind, email, created_at, expires_at, used_at, superseded_at
`

type UseEmailLinkParams struct {
	TokenHash []byte `json:"token_hash"`
	Kind      string `json:"kind"`
}

// Spending a link. Checking it and marking it used are ONE statement, so two
// tabs submitting the same link at once cannot both succeed: the second finds
// used_at already set and gets no row.
func (q *Queries) UseEmailLink(ctx context.Context, arg UseEmailLinkParams) (EmailLink, error) {
	row := q.db.QueryRow(ctx, useEmailLink, arg.TokenHash, arg.Kind)
	var i EmailLink
	err := row.Scan(
		&i.TokenHash,
		&i.Kind,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.SupersededAt,
	)
	return i, err
}
