// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationUsage = `-- name: AddConversationUsage :one
UPDATE conversations
SET tokens = tokens + $2, spend_ticks = spend_ticks + $3, updated_at = now()
WHERE id = $1
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type AddConversationUsageParams struct {
	ID         pgtype.UUID `json:"id"`
	Tokens     int64       `json:"tokens"`
	SpendTicks int64       `json:"spend_ticks"`
}

func (q *Queries) AddConversationUsage(ctx context.Context, arg AddConversationUsageParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, addConversationUsage, arg.ID, arg.Tokens, arg.SpendTicks)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (folder, provider, model_id, model_label)
VALUES ($1, $2, $3, $4)
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type CreateConversationParams struct {
	Folder     string `json:"folder"`
	Provider   string `json:"provider"`
	ModelID    string `json:"model_id"`
	ModelLabel string `json:"model_label"`
}

// A new conversation has no name. It gets one from the first thing said in it,
// or from the owner typing one — never from a default that only looks like a
// title.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.Folder,
		arg.Provider,
		arg.ModelID,
		arg.ModelLabel,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const deleteConversationEntries = `-- name: DeleteConversationEntries :exec
DELETE FROM entries WHERE conversation_id = $1
`

func (q *Queries) DeleteConversationEntries(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationEntries, conversationID)
	return err
}

const deleteConversationProviderSessions = `-- name: DeleteConversationProviderSessions :exec
DELETE FROM provider_sessions WHERE conversation_id = $1
`

func (q *Queries) DeleteConversationProviderSessions(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationProviderSessions, conversationID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at FROM conversations
ORDER BY updated_at DESC
`

func (q *Queries) ListConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Folder,
			&i.Provider,
			&i.ModelID,
			&i.ModelLabel,
			&i.Archived,
			&i.SpendTicks,
			&i.Tokens,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nameConversation = `-- name: NameConversation :one
UPDATE conversations SET title = $2
WHERE id = $1 AND title IS NULL
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type NameConversationParams struct {
	ID    pgtype.UUID `json:"id"`
	Title *string     `json:"title"`
}

// Naming, as opposed to renaming: this only ever fills a blank. The guard is in
// the statement rather than in Go so that a name the owner typed can never be
// overwritten by one derived from a message, whatever order the two arrive in.
// No rows means it already had a name, which is an outcome and not an error.
func (q *Queries) NameConversation(ctx context.Context, arg NameConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, nameConversation, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recentFolders = `-- name: RecentFolders :many
SELECT folder, max(updated_at) AS last_used
FROM conversations
GROUP BY folder
ORDER BY last_used DESC
LIMIT $1
`

type RecentFoldersRow struct {
	Folder   string      `json:"folder"`
	LastUsed interface{} `json:"last_used"`
}

// Folders already in use, most recently touched first. The picker's shortcut
// list, and the default for a new conversation — both come free from
// conversations that already exist rather than from a preference to maintain.
func (q *Queries) RecentFolders(ctx context.Context, limit int32) ([]RecentFoldersRow, error) {
	rows, err := q.db.Query(ctx, recentFolders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentFoldersRow{}
	for rows.Next() {
		var i RecentFoldersRow
		if err := rows.Scan(&i.Folder, &i.LastUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameConversation = `-- name: RenameConversation :one
UPDATE conversations SET title = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type RenameConversationParams struct {
	ID    pgtype.UUID `json:"id"`
	Title *string     `json:"title"`
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, renameConversation, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConversationArchived = `-- name: SetConversationArchived :one
UPDATE conversations SET archived = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type SetConversationArchivedParams struct {
	ID       pgtype.UUID `json:"id"`
	Archived bool        `json:"archived"`
}

func (q *Queries) SetConversationArchived(ctx context.Context, arg SetConversationArchivedParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationArchived, arg.ID, arg.Archived)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConversationFolder = `-- name: SetConversationFolder :one
UPDATE conversations SET folder = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type SetConversationFolderParams struct {
	ID     pgtype.UUID `json:"id"`
	Folder string      `json:"folder"`
}

func (q *Queries) SetConversationFolder(ctx context.Context, arg SetConversationFolderParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationFolder, arg.ID, arg.Folder)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConversationProvider = `-- name: SetConversationProvider :one
UPDATE conversations
SET provider = $2, model_id = $3, model_label = $4, updated_at = now()
WHERE id = $1
RETURNING id, title, folder, provider, model_id, model_label, archived, spend_ticks, tokens, created_at, updated_at
`

type SetConversationProviderParams struct {
	ID         pgtype.UUID `json:"id"`
	Provider   string      `json:"provider"`
	ModelID    string      `json:"model_id"`
	ModelLabel string      `json:"model_label"`
}

func (q *Queries) SetConversationProvider(ctx context.Context, arg SetConversationProviderParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationProvider,
		arg.ID,
		arg.Provider,
		arg.ModelID,
		arg.ModelLabel,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Folder,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Archived,
		&i.SpendTicks,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
