// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEntry = `-- name: AppendEntry :one
INSERT INTO entries (
    conversation_id, seq, role, body,
    provider, model_id, model_label,
    tokens, spend_ticks, failure, messages_replayed
) VALUES (
    $1,
    (SELECT COALESCE(MAX(seq), 0) + 1 FROM entries WHERE conversation_id = $1),
    $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, conversation_id, seq, role, body, created_at, provider, model_id, model_label, tokens, spend_ticks, failure, messages_replayed, stopped, finished_at
`

type AppendEntryParams struct {
	ConversationID   pgtype.UUID `json:"conversation_id"`
	Role             string      `json:"role"`
	Body             string      `json:"body"`
	Provider         *string     `json:"provider"`
	ModelID          *string     `json:"model_id"`
	ModelLabel       *string     `json:"model_label"`
	Tokens           *int64      `json:"tokens"`
	SpendTicks       *int64      `json:"spend_ticks"`
	Failure          *string     `json:"failure"`
	MessagesReplayed *int32      `json:"messages_replayed"`
}

// seq is allocated inside the statement so two concurrent appends cannot pick
// the same number. The unique constraint would catch it; this avoids the retry.
func (q *Queries) AppendEntry(ctx context.Context, arg AppendEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, appendEntry,
		arg.ConversationID,
		arg.Role,
		arg.Body,
		arg.Provider,
		arg.ModelID,
		arg.ModelLabel,
		arg.Tokens,
		arg.SpendTicks,
		arg.Failure,
		arg.MessagesReplayed,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.Body,
		&i.CreatedAt,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Tokens,
		&i.SpendTicks,
		&i.Failure,
		&i.MessagesReplayed,
		&i.Stopped,
		&i.FinishedAt,
	)
	return i, err
}

const appendEntryBody = `-- name: AppendEntryBody :one
UPDATE entries
SET body = body || $2::text
WHERE id = $1
RETURNING id, conversation_id, seq, role, body, created_at, provider, model_id, model_label, tokens, spend_ticks, failure, messages_replayed, stopped, finished_at
`

type AppendEntryBodyParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 string      `json:"column_2"`
}

// Streaming deltas are accumulated in place rather than kept only in memory, so
// a refresh mid-turn does not lose what has already arrived.
func (q *Queries) AppendEntryBody(ctx context.Context, arg AppendEntryBodyParams) (Entry, error) {
	row := q.db.QueryRow(ctx, appendEntryBody, arg.ID, arg.Column2)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.Body,
		&i.CreatedAt,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Tokens,
		&i.SpendTicks,
		&i.Failure,
		&i.MessagesReplayed,
		&i.Stopped,
		&i.FinishedAt,
	)
	return i, err
}

const countEntries = `-- name: CountEntries :one
SELECT COUNT(*) FROM entries WHERE conversation_id = $1
`

func (q *Queries) CountEntries(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEntries, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishAgentEntry = `-- name: FinishAgentEntry :one
UPDATE entries
SET body = $2, tokens = $3, spend_ticks = $4, failure = $5, stopped = $6,
    finished_at = now()
WHERE id = $1
RETURNING id, conversation_id, seq, role, body, created_at, provider, model_id, model_label, tokens, spend_ticks, failure, messages_replayed, stopped, finished_at
`

type FinishAgentEntryParams struct {
	ID         pgtype.UUID `json:"id"`
	Body       string      `json:"body"`
	Tokens     *int64      `json:"tokens"`
	SpendTicks *int64      `json:"spend_ticks"`
	Failure    *string     `json:"failure"`
	Stopped    bool        `json:"stopped"`
}

// finished_at is stamped here rather than left as created_at, which is when the
// empty entry was opened for the turn to stream into. The transcript shows when
// the answer arrived (docs/Bugs.md B-35).
func (q *Queries) FinishAgentEntry(ctx context.Context, arg FinishAgentEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, finishAgentEntry,
		arg.ID,
		arg.Body,
		arg.Tokens,
		arg.SpendTicks,
		arg.Failure,
		arg.Stopped,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.Body,
		&i.CreatedAt,
		&i.Provider,
		&i.ModelID,
		&i.ModelLabel,
		&i.Tokens,
		&i.SpendTicks,
		&i.Failure,
		&i.MessagesReplayed,
		&i.Stopped,
		&i.FinishedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, conversation_id, seq, role, body, created_at, provider, model_id, model_label, tokens, spend_ticks, failure, messages_replayed, stopped, finished_at FROM entries
WHERE conversation_id = $1
ORDER BY seq
`

func (q *Queries) ListEntries(ctx context.Context, conversationID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Body,
			&i.CreatedAt,
			&i.Provider,
			&i.ModelID,
			&i.ModelLabel,
			&i.Tokens,
			&i.SpendTicks,
			&i.Failure,
			&i.MessagesReplayed,
			&i.Stopped,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesFrom = `-- name: ListEntriesFrom :many
SELECT id, conversation_id, seq, role, body, created_at, provider, model_id, model_label, tokens, spend_ticks, failure, messages_replayed, stopped, finished_at FROM entries
WHERE conversation_id = $1 AND seq > $2
ORDER BY seq
`

type ListEntriesFromParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Seq            int32       `json:"seq"`
}

// The replay payload: everything a provider has not been told yet.
func (q *Queries) ListEntriesFrom(ctx context.Context, arg ListEntriesFromParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesFrom, arg.ConversationID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Body,
			&i.CreatedAt,
			&i.Provider,
			&i.ModelID,
			&i.ModelLabel,
			&i.Tokens,
			&i.SpendTicks,
			&i.Failure,
			&i.MessagesReplayed,
			&i.Stopped,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
