// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchanges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentEntryFor = `-- name: AgentEntryFor :one
SELECT e.id, e.conversation_id, COALESCE(e.provider, '')::text AS provider
FROM entries e
JOIN conversations c ON c.id = e.conversation_id
WHERE e.id = $1
  AND e.role = 'agent'
  AND EXISTS (
      SELECT 1 FROM workspace_members m
      WHERE m.workspace_id = c.workspace_id AND m.user_id = $2
  )
`

type AgentEntryForParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type AgentEntryForRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Provider       string      `json:"provider"`
}

// An agent entry, only if it is in a conversation this account can see. The
// ownership check for reading a record.
func (q *Queries) AgentEntryFor(ctx context.Context, arg AgentEntryForParams) (AgentEntryForRow, error) {
	row := q.db.QueryRow(ctx, agentEntryFor, arg.ID, arg.UserID)
	var i AgentEntryForRow
	err := row.Scan(&i.ID, &i.ConversationID, &i.Provider)
	return i, err
}

const appendExchangeLines = `-- name: AppendExchangeLines :exec
WITH stored AS (
    INSERT INTO exchange_lines (entry_id, seq, at_ms, stream, body)
    SELECT $1::uuid,
           unnest($2::integer[]),
           unnest($3::bigint[]),
           unnest($4::text[]),
           unnest($5::text[])
    ON CONFLICT (entry_id, seq) DO NOTHING
    RETURNING at_ms, octet_length(body) AS bytes
)
UPDATE exchanges
SET line_count = line_count + (SELECT count(*) FROM stored),
    byte_count = byte_count + COALESCE((SELECT sum(bytes) FROM stored), 0),
    last_at_ms = GREATEST(last_at_ms, COALESCE((SELECT max(at_ms) FROM stored), 0))
WHERE exchanges.entry_id = $1::uuid
`

type AppendExchangeLinesParams struct {
	EntryID pgtype.UUID `json:"entry_id"`
	Seqs    []int32     `json:"seqs"`
	AtMs    []int64     `json:"at_ms"`
	Streams []string    `json:"streams"`
	Bodies  []string    `json:"bodies"`
}

// One batch in one statement: the four arrays are stepped through in lockstep,
// which is what several unnests in one select list do. A repeated seq is a
// batch already stored, and is skipped rather than failing the ones around it,
// and only the lines actually stored move the record's totals.
func (q *Queries) AppendExchangeLines(ctx context.Context, arg AppendExchangeLinesParams) error {
	_, err := q.db.Exec(ctx, appendExchangeLines,
		arg.EntryID,
		arg.Seqs,
		arg.AtMs,
		arg.Streams,
		arg.Bodies,
	)
	return err
}

const deleteConversationContextDocuments = `-- name: DeleteConversationContextDocuments :exec
DELETE FROM context_documents WHERE conversation_id = $1
`

func (q *Queries) DeleteConversationContextDocuments(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationContextDocuments, conversationID)
	return err
}

const deleteConversationExchangeContext = `-- name: DeleteConversationExchangeContext :exec
DELETE FROM exchange_context WHERE conversation_id = $1
`

func (q *Queries) DeleteConversationExchangeContext(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationExchangeContext, conversationID)
	return err
}

const deleteConversationExchangeLines = `-- name: DeleteConversationExchangeLines :exec
DELETE FROM exchange_lines
WHERE entry_id IN (SELECT entry_id FROM exchanges WHERE conversation_id = $1)
`

func (q *Queries) DeleteConversationExchangeLines(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationExchangeLines, conversationID)
	return err
}

const deleteConversationExchanges = `-- name: DeleteConversationExchanges :exec
DELETE FROM exchanges WHERE conversation_id = $1
`

func (q *Queries) DeleteConversationExchanges(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationExchanges, conversationID)
	return err
}

const deleteEveryContextDocument = `-- name: DeleteEveryContextDocument :exec
DELETE FROM context_documents
`

func (q *Queries) DeleteEveryContextDocument(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryContextDocument)
	return err
}

const deleteEveryExchange = `-- name: DeleteEveryExchange :exec
DELETE FROM exchanges
`

func (q *Queries) DeleteEveryExchange(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryExchange)
	return err
}

const deleteEveryExchangeContext = `-- name: DeleteEveryExchangeContext :exec
DELETE FROM exchange_context
`

// Tests only, with the other DeleteEvery* in users.sql.
func (q *Queries) DeleteEveryExchangeContext(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryExchangeContext)
	return err
}

const deleteEveryExchangeLine = `-- name: DeleteEveryExchangeLine :exec
DELETE FROM exchange_lines
`

// Tests only, with the other DeleteEvery* in users.sql.
func (q *Queries) DeleteEveryExchangeLine(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryExchangeLine)
	return err
}

const getExchange = `-- name: GetExchange :one
SELECT entry_id, conversation_id, program, args, cwd, resume_session_id, prompt, stdin, launched, dropped_lines, dropped_bytes, line_count, byte_count, last_at_ms, created_at, context_read, context_from, context_error FROM exchanges WHERE entry_id = $1
`

func (q *Queries) GetExchange(ctx context.Context, entryID pgtype.UUID) (Exchange, error) {
	row := q.db.QueryRow(ctx, getExchange, entryID)
	var i Exchange
	err := row.Scan(
		&i.EntryID,
		&i.ConversationID,
		&i.Program,
		&i.Args,
		&i.Cwd,
		&i.ResumeSessionID,
		&i.Prompt,
		&i.Stdin,
		&i.Launched,
		&i.DroppedLines,
		&i.DroppedBytes,
		&i.LineCount,
		&i.ByteCount,
		&i.LastAtMs,
		&i.CreatedAt,
		&i.ContextRead,
		&i.ContextFrom,
		&i.ContextError,
	)
	return i, err
}

const linkExchangeContext = `-- name: LinkExchangeContext :exec
INSERT INTO exchange_context (entry_id, ord, conversation_id, hash)
SELECT $1::uuid,
       unnest($2::integer[]),
       $3::uuid,
       unnest($4::bytea[])
ON CONFLICT (entry_id, ord) DO NOTHING
`

type LinkExchangeContextParams struct {
	EntryID        pgtype.UUID `json:"entry_id"`
	Ords           []int32     `json:"ords"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Hashes         [][]byte    `json:"hashes"`
}

func (q *Queries) LinkExchangeContext(ctx context.Context, arg LinkExchangeContextParams) error {
	_, err := q.db.Exec(ctx, linkExchangeContext,
		arg.EntryID,
		arg.Ords,
		arg.ConversationID,
		arg.Hashes,
	)
	return err
}

const listExchangeContext = `-- name: ListExchangeContext :many
SELECT d.kind, d.body
FROM exchange_context c
JOIN context_documents d ON d.conversation_id = c.conversation_id AND d.hash = c.hash
WHERE c.entry_id = $1
ORDER BY c.ord
`

type ListExchangeContextRow struct {
	Kind string `json:"kind"`
	Body string `json:"body"`
}

func (q *Queries) ListExchangeContext(ctx context.Context, entryID pgtype.UUID) ([]ListExchangeContextRow, error) {
	rows, err := q.db.Query(ctx, listExchangeContext, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExchangeContextRow{}
	for rows.Next() {
		var i ListExchangeContextRow
		if err := rows.Scan(&i.Kind, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangeLines = `-- name: ListExchangeLines :many
SELECT entry_id, seq, at_ms, stream, body FROM exchange_lines WHERE entry_id = $1 ORDER BY seq
`

func (q *Queries) ListExchangeLines(ctx context.Context, entryID pgtype.UUID) ([]ExchangeLine, error) {
	rows, err := q.db.Query(ctx, listExchangeLines, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeLine{}
	for rows.Next() {
		var i ExchangeLine
		if err := rows.Scan(
			&i.EntryID,
			&i.Seq,
			&i.AtMs,
			&i.Stream,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangeSummaries = `-- name: ListExchangeSummaries :many
SELECT entry_id, launched, line_count, byte_count, last_at_ms, dropped_lines, dropped_bytes
FROM exchanges
WHERE conversation_id = $1
`

type ListExchangeSummariesRow struct {
	EntryID      pgtype.UUID `json:"entry_id"`
	Launched     bool        `json:"launched"`
	LineCount    int32       `json:"line_count"`
	ByteCount    int64       `json:"byte_count"`
	LastAtMs     int64       `json:"last_at_ms"`
	DroppedLines int64       `json:"dropped_lines"`
	DroppedBytes int64       `json:"dropped_bytes"`
}

// How big each turn's record in one conversation is, without reading any of it.
func (q *Queries) ListExchangeSummaries(ctx context.Context, conversationID pgtype.UUID) ([]ListExchangeSummariesRow, error) {
	rows, err := q.db.Query(ctx, listExchangeSummaries, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExchangeSummariesRow{}
	for rows.Next() {
		var i ListExchangeSummariesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.Launched,
			&i.LineCount,
			&i.ByteCount,
			&i.LastAtMs,
			&i.DroppedLines,
			&i.DroppedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putContextDocuments = `-- name: PutContextDocuments :exec
INSERT INTO context_documents (conversation_id, hash, kind, body)
SELECT $1::uuid,
       unnest($2::bytea[]),
       unnest($3::text[]),
       unnest($4::text[])
ON CONFLICT (conversation_id, hash) DO NOTHING
`

type PutContextDocumentsParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Hashes         [][]byte    `json:"hashes"`
	Kinds          []string    `json:"kinds"`
	Bodies         []string    `json:"bodies"`
}

// A record this conversation already holds is kept, not stored again.
func (q *Queries) PutContextDocuments(ctx context.Context, arg PutContextDocumentsParams) error {
	_, err := q.db.Exec(ctx, putContextDocuments,
		arg.ConversationID,
		arg.Hashes,
		arg.Kinds,
		arg.Bodies,
	)
	return err
}

const recordExchange = `-- name: RecordExchange :exec
INSERT INTO exchanges (
    entry_id, conversation_id, program, args, cwd, resume_session_id, prompt, stdin, launched
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (entry_id) DO NOTHING
`

type RecordExchangeParams struct {
	EntryID         pgtype.UUID `json:"entry_id"`
	ConversationID  pgtype.UUID `json:"conversation_id"`
	Program         string      `json:"program"`
	Args            []string    `json:"args"`
	Cwd             string      `json:"cwd"`
	ResumeSessionID string      `json:"resume_session_id"`
	Prompt          string      `json:"prompt"`
	Stdin           string      `json:"stdin"`
	Launched        bool        `json:"launched"`
}

// Once per turn. A daemon that sent it twice (it never should) changes nothing.
func (q *Queries) RecordExchange(ctx context.Context, arg RecordExchangeParams) error {
	_, err := q.db.Exec(ctx, recordExchange,
		arg.EntryID,
		arg.ConversationID,
		arg.Program,
		arg.Args,
		arg.Cwd,
		arg.ResumeSessionID,
		arg.Prompt,
		arg.Stdin,
		arg.Launched,
	)
	return err
}

const setExchangeContext = `-- name: SetExchangeContext :exec
UPDATE exchanges
SET context_read = true, context_from = $1, context_error = $2
WHERE entry_id = $3
`

type SetExchangeContextParams struct {
	ContextFrom  string      `json:"context_from"`
	ContextError string      `json:"context_error"`
	EntryID      pgtype.UUID `json:"entry_id"`
}

func (q *Queries) SetExchangeContext(ctx context.Context, arg SetExchangeContextParams) error {
	_, err := q.db.Exec(ctx, setExchangeContext, arg.ContextFrom, arg.ContextError, arg.EntryID)
	return err
}

const setExchangeDropped = `-- name: SetExchangeDropped :exec
UPDATE exchanges
SET dropped_lines = $1, dropped_bytes = $2
WHERE entry_id = $3
`

type SetExchangeDroppedParams struct {
	DroppedLines int64       `json:"dropped_lines"`
	DroppedBytes int64       `json:"dropped_bytes"`
	EntryID      pgtype.UUID `json:"entry_id"`
}

// The daemon sends running totals, so this sets rather than adds.
func (q *Queries) SetExchangeDropped(ctx context.Context, arg SetExchangeDroppedParams) error {
	_, err := q.db.Exec(ctx, setExchangeDropped, arg.DroppedLines, arg.DroppedBytes, arg.EntryID)
	return err
}
