// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favourite_models.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavouriteModel = `-- name: AddFavouriteModel :exec
INSERT INTO favourite_models (user_id, provider, model)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, provider, model) DO NOTHING
`

type AddFavouriteModelParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
	Model    string      `json:"model"`
}

// Starring one already starred keeps its place.
func (q *Queries) AddFavouriteModel(ctx context.Context, arg AddFavouriteModelParams) error {
	_, err := q.db.Exec(ctx, addFavouriteModel, arg.UserID, arg.Provider, arg.Model)
	return err
}

const countFavouriteModels = `-- name: CountFavouriteModels :one
SELECT count(*) FROM favourite_models WHERE user_id = $1
`

func (q *Queries) CountFavouriteModels(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavouriteModels, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listFavouriteModels = `-- name: ListFavouriteModels :many
SELECT provider, model FROM favourite_models
WHERE user_id = $1
ORDER BY created_at, provider, model
`

type ListFavouriteModelsRow struct {
	Provider string `json:"provider"`
	Model    string `json:"model"`
}

// Oldest first: a newly starred model goes to the end, where it was put.
func (q *Queries) ListFavouriteModels(ctx context.Context, userID pgtype.UUID) ([]ListFavouriteModelsRow, error) {
	rows, err := q.db.Query(ctx, listFavouriteModels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavouriteModelsRow{}
	for rows.Next() {
		var i ListFavouriteModelsRow
		if err := rows.Scan(&i.Provider, &i.Model); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavouriteModel = `-- name: RemoveFavouriteModel :exec
DELETE FROM favourite_models WHERE user_id = $1 AND provider = $2 AND model = $3
`

type RemoveFavouriteModelParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
	Model    string      `json:"model"`
}

func (q *Queries) RemoveFavouriteModel(ctx context.Context, arg RemoveFavouriteModelParams) error {
	_, err := q.db.Exec(ctx, removeFavouriteModel, arg.UserID, arg.Provider, arg.Model)
	return err
}
