// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachConversationFiles = `-- name: AttachConversationFiles :many
UPDATE conversation_files
SET entry_id = $1
WHERE id = ANY($2::uuid[])
  AND conversation_id = $3
  AND origin = 'upload'
  AND entry_id IS NULL
RETURNING id, conversation_id, entry_id, origin, name, media_type, size, sha256, created_at
`

type AttachConversationFilesParams struct {
	EntryID        pgtype.UUID   `json:"entry_id"`
	Ids            []pgtype.UUID `json:"ids"`
	ConversationID pgtype.UUID   `json:"conversation_id"`
}

// Sending a message takes the uploads waiting in its box. Only this
// conversation's, only uploads, and only ones not already sent with another.
func (q *Queries) AttachConversationFiles(ctx context.Context, arg AttachConversationFilesParams) ([]ConversationFile, error) {
	rows, err := q.db.Query(ctx, attachConversationFiles, arg.EntryID, arg.Ids, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationFile{}
	for rows.Next() {
		var i ConversationFile
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.EntryID,
			&i.Origin,
			&i.Name,
			&i.MediaType,
			&i.Size,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conversationFileContent = `-- name: ConversationFileContent :one
SELECT content FROM conversation_file_contents WHERE file_id = $1
`

func (q *Queries) ConversationFileContent(ctx context.Context, fileID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, conversationFileContent, fileID)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const conversationFileFor = `-- name: ConversationFileFor :one
SELECT f.id, f.conversation_id, f.entry_id, f.origin, f.name, f.media_type, f.size, f.sha256, f.created_at FROM conversation_files f
JOIN conversations c ON c.id = f.conversation_id
WHERE f.id = $1
  AND EXISTS (
      SELECT 1 FROM workspace_members m
      WHERE m.workspace_id = c.workspace_id AND m.user_id = $2
  )
`

type ConversationFileForParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// One file, only if it is in a conversation this account can see. The
// ownership check for every read of a file, from the browser or a computer.
func (q *Queries) ConversationFileFor(ctx context.Context, arg ConversationFileForParams) (ConversationFile, error) {
	row := q.db.QueryRow(ctx, conversationFileFor, arg.ID, arg.UserID)
	var i ConversationFile
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EntryID,
		&i.Origin,
		&i.Name,
		&i.MediaType,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const conversationFileNames = `-- name: ConversationFileNames :many
SELECT name FROM conversation_files
WHERE conversation_id = $1 AND origin = $2
`

type ConversationFileNamesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Origin         string      `json:"origin"`
}

// The names already used in one of a conversation's two folders, so a new
// file can be given one that is free.
func (q *Queries) ConversationFileNames(ctx context.Context, arg ConversationFileNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, conversationFileNames, arg.ConversationID, arg.Origin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConversationFile = `-- name: CreateConversationFile :one
INSERT INTO conversation_files (conversation_id, entry_id, origin, name, media_type, size, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, conversation_id, entry_id, origin, name, media_type, size, sha256, created_at
`

type CreateConversationFileParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	EntryID        pgtype.UUID `json:"entry_id"`
	Origin         string      `json:"origin"`
	Name           string      `json:"name"`
	MediaType      string      `json:"media_type"`
	Size           int64       `json:"size"`
	Sha256         string      `json:"sha256"`
}

func (q *Queries) CreateConversationFile(ctx context.Context, arg CreateConversationFileParams) (ConversationFile, error) {
	row := q.db.QueryRow(ctx, createConversationFile,
		arg.ConversationID,
		arg.EntryID,
		arg.Origin,
		arg.Name,
		arg.MediaType,
		arg.Size,
		arg.Sha256,
	)
	var i ConversationFile
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EntryID,
		&i.Origin,
		&i.Name,
		&i.MediaType,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversationFileContent = `-- name: DeleteConversationFileContent :exec
DELETE FROM conversation_file_contents WHERE file_id = $1
`

func (q *Queries) DeleteConversationFileContent(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationFileContent, fileID)
	return err
}

const deleteConversationFileContents = `-- name: DeleteConversationFileContents :exec
DELETE FROM conversation_file_contents
WHERE file_id IN (SELECT id FROM conversation_files WHERE conversation_id = $1)
`

func (q *Queries) DeleteConversationFileContents(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationFileContents, conversationID)
	return err
}

const deleteConversationFiles = `-- name: DeleteConversationFiles :exec
DELETE FROM conversation_files WHERE conversation_id = $1
`

func (q *Queries) DeleteConversationFiles(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationFiles, conversationID)
	return err
}

const deleteEveryConversationFile = `-- name: DeleteEveryConversationFile :exec
DELETE FROM conversation_files
`

func (q *Queries) DeleteEveryConversationFile(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryConversationFile)
	return err
}

const deleteEveryConversationFileContent = `-- name: DeleteEveryConversationFileContent :exec
DELETE FROM conversation_file_contents
`

func (q *Queries) DeleteEveryConversationFileContent(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryConversationFileContent)
	return err
}

const deleteUnsentConversationFile = `-- name: DeleteUnsentConversationFile :execrows
DELETE FROM conversation_files WHERE id = $1 AND entry_id IS NULL AND origin = 'upload'
`

// Removing an upload from the box. Once sent, a file is part of the record.
func (q *Queries) DeleteUnsentConversationFile(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnsentConversationFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConversationFiles = `-- name: ListConversationFiles :many
SELECT id, conversation_id, entry_id, origin, name, media_type, size, sha256, created_at FROM conversation_files
WHERE conversation_id = $1
ORDER BY created_at DESC, name
`

// Newest first, which is the order the pane shows them in.
func (q *Queries) ListConversationFiles(ctx context.Context, conversationID pgtype.UUID) ([]ConversationFile, error) {
	rows, err := q.db.Query(ctx, listConversationFiles, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationFile{}
	for rows.Next() {
		var i ConversationFile
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.EntryID,
			&i.Origin,
			&i.Name,
			&i.MediaType,
			&i.Size,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putConversationFileContent = `-- name: PutConversationFileContent :exec
INSERT INTO conversation_file_contents (file_id, content) VALUES ($1, $2)
`

type PutConversationFileContentParams struct {
	FileID  pgtype.UUID `json:"file_id"`
	Content []byte      `json:"content"`
}

func (q *Queries) PutConversationFileContent(ctx context.Context, arg PutConversationFileContentParams) error {
	_, err := q.db.Exec(ctx, putConversationFileContent, arg.FileID, arg.Content)
	return err
}
