// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveMachine = `-- name: ApproveMachine :one
UPDATE machines
SET approved_at = now()
WHERE id = $1::uuid AND user_id = $2::uuid AND revoked_at IS NULL
RETURNING id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version
`

type ApproveMachineParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) ApproveMachine(ctx context.Context, arg ApproveMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, approveMachine, arg.Column1, arg.Column2)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const approveMachinePairing = `-- name: ApproveMachinePairing :one
UPDATE machine_pairings
SET status = 'approved', decided_at = now()
WHERE id = $1::uuid AND user_id = $2::uuid AND status = 'claimed' AND expires_at > now()
RETURNING id, user_id, token_hash, status, machine_id, created_at, expires_at, claimed_at, decided_at
`

type ApproveMachinePairingParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) ApproveMachinePairing(ctx context.Context, arg ApproveMachinePairingParams) (MachinePairing, error) {
	row := q.db.QueryRow(ctx, approveMachinePairing, arg.Column1, arg.Column2)
	var i MachinePairing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Status,
		&i.MachineID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.DecidedAt,
	)
	return i, err
}

const approvedMachineForUserCredential = `-- name: ApprovedMachineForUserCredential :one
SELECT id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version FROM machines
WHERE credential_hash = $1 AND user_id = $2 AND approved_at IS NOT NULL AND revoked_at IS NULL
`

type ApprovedMachineForUserCredentialParams struct {
	CredentialHash []byte      `json:"credential_hash"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) ApprovedMachineForUserCredential(ctx context.Context, arg ApprovedMachineForUserCredentialParams) (Machine, error) {
	row := q.db.QueryRow(ctx, approvedMachineForUserCredential, arg.CredentialHash, arg.UserID)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const claimMachinePairing = `-- name: ClaimMachinePairing :one
UPDATE machine_pairings
SET status = 'claimed', machine_id = $2, claimed_at = now()
WHERE token_hash = $1 AND status = 'pending' AND expires_at > now()
RETURNING id, user_id, token_hash, status, machine_id, created_at, expires_at, claimed_at, decided_at
`

type ClaimMachinePairingParams struct {
	TokenHash []byte      `json:"token_hash"`
	MachineID pgtype.UUID `json:"machine_id"`
}

func (q *Queries) ClaimMachinePairing(ctx context.Context, arg ClaimMachinePairingParams) (MachinePairing, error) {
	row := q.db.QueryRow(ctx, claimMachinePairing, arg.TokenHash, arg.MachineID)
	var i MachinePairing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Status,
		&i.MachineID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.DecidedAt,
	)
	return i, err
}

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (user_id, display_name, credential_hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version
`

type CreateMachineParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	DisplayName    string      `json:"display_name"`
	CredentialHash []byte      `json:"credential_hash"`
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, createMachine, arg.UserID, arg.DisplayName, arg.CredentialHash)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const createMachinePairing = `-- name: CreateMachinePairing :one
INSERT INTO machine_pairings (user_id, token_hash, status, expires_at)
VALUES ($1, $2, 'pending', $3)
RETURNING id, user_id, token_hash, status, machine_id, created_at, expires_at, claimed_at, decided_at
`

type CreateMachinePairingParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMachinePairing(ctx context.Context, arg CreateMachinePairingParams) (MachinePairing, error) {
	row := q.db.QueryRow(ctx, createMachinePairing, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i MachinePairing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Status,
		&i.MachineID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.DecidedAt,
	)
	return i, err
}

const credentialRefused = `-- name: CredentialRefused :one
SELECT (m.revoked_at IS NOT NULL OR (m.approved_at IS NULL AND NOT EXISTS (
    SELECT 1 FROM machine_pairings p
    WHERE p.machine_id = m.id AND p.status = 'claimed' AND p.expires_at > now()
)))::boolean AS refused
FROM machines m
WHERE m.credential_hash = $1
`

// A credential that can never connect: its computer was disconnected, or it
// was never approved and can no longer be, because its pairing was declined
// or has expired.
func (q *Queries) CredentialRefused(ctx context.Context, credentialHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, credentialRefused, credentialHash)
	var refused bool
	err := row.Scan(&refused)
	return refused, err
}

const declineMachinePairing = `-- name: DeclineMachinePairing :one
UPDATE machine_pairings
SET status = 'rejected', decided_at = now()
WHERE id = $1::uuid AND user_id = $2::uuid AND status IN ('pending', 'claimed')
RETURNING id, user_id, token_hash, status, machine_id, created_at, expires_at, claimed_at, decided_at
`

type DeclineMachinePairingParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) DeclineMachinePairing(ctx context.Context, arg DeclineMachinePairingParams) (MachinePairing, error) {
	row := q.db.QueryRow(ctx, declineMachinePairing, arg.Column1, arg.Column2)
	var i MachinePairing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Status,
		&i.MachineID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getMachineForUser = `-- name: GetMachineForUser :one
SELECT id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version FROM machines
WHERE id = $1::uuid AND user_id = $2::uuid AND approved_at IS NOT NULL AND revoked_at IS NULL
`

type GetMachineForUserParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) GetMachineForUser(ctx context.Context, arg GetMachineForUserParams) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineForUser, arg.Column1, arg.Column2)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const getMachinePairingForUser = `-- name: GetMachinePairingForUser :one
SELECT id, user_id, token_hash, status, machine_id, created_at, expires_at, claimed_at, decided_at FROM machine_pairings WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetMachinePairingForUserParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) GetMachinePairingForUser(ctx context.Context, arg GetMachinePairingForUserParams) (MachinePairing, error) {
	row := q.db.QueryRow(ctx, getMachinePairingForUser, arg.Column1, arg.Column2)
	var i MachinePairing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Status,
		&i.MachineID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version FROM machines
WHERE user_id = $1::uuid AND approved_at IS NOT NULL AND revoked_at IS NULL
ORDER BY created_at DESC
`

// Only approved computers. One still waiting for approval belongs to the
// pairing in progress, not to the account's list.
func (q *Queries) ListMachines(ctx context.Context, dollar_1 pgtype.UUID) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachines, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.CredentialHash,
			&i.ApprovedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AutomaticUpdates,
			&i.DaemonVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const machineByCredential = `-- name: MachineByCredential :one
SELECT id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version FROM machines
WHERE credential_hash = $1 AND approved_at IS NOT NULL AND revoked_at IS NULL
`

func (q *Queries) MachineByCredential(ctx context.Context, credentialHash []byte) (Machine, error) {
	row := q.db.QueryRow(ctx, machineByCredential, credentialHash)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const markPairingAlreadyPaired = `-- name: MarkPairingAlreadyPaired :one
UPDATE machine_pairings
SET status = 'approved', machine_id = $2, claimed_at = now(), decided_at = now()
WHERE token_hash = $1 AND status = 'pending' AND expires_at > now()
RETURNING id, user_id, token_hash, status, machine_id, created_at, expires_at, claimed_at, decided_at
`

type MarkPairingAlreadyPairedParams struct {
	TokenHash []byte      `json:"token_hash"`
	MachineID pgtype.UUID `json:"machine_id"`
}

// The computer presenting this request is already approved for the same
// account, so the request resolves to that computer instead of a duplicate.
func (q *Queries) MarkPairingAlreadyPaired(ctx context.Context, arg MarkPairingAlreadyPairedParams) (MachinePairing, error) {
	row := q.db.QueryRow(ctx, markPairingAlreadyPaired, arg.TokenHash, arg.MachineID)
	var i MachinePairing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Status,
		&i.MachineID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.DecidedAt,
	)
	return i, err
}

const recordMachineVersion = `-- name: RecordMachineVersion :exec
UPDATE machines SET daemon_version = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RecordMachineVersionParams struct {
	ID            pgtype.UUID `json:"id"`
	DaemonVersion *string     `json:"daemon_version"`
}

func (q *Queries) RecordMachineVersion(ctx context.Context, arg RecordMachineVersionParams) error {
	_, err := q.db.Exec(ctx, recordMachineVersion, arg.ID, arg.DaemonVersion)
	return err
}

const revokeMachine = `-- name: RevokeMachine :one
UPDATE machines
SET revoked_at = now()
WHERE id = $1::uuid AND user_id = $2::uuid AND revoked_at IS NULL
RETURNING id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version
`

type RevokeMachineParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) RevokeMachine(ctx context.Context, arg RevokeMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, revokeMachine, arg.Column1, arg.Column2)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const revokeUnapprovedMachine = `-- name: RevokeUnapprovedMachine :exec
UPDATE machines
SET revoked_at = now()
WHERE id = $1::uuid AND user_id = $2::uuid AND approved_at IS NULL AND revoked_at IS NULL
`

type RevokeUnapprovedMachineParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) RevokeUnapprovedMachine(ctx context.Context, arg RevokeUnapprovedMachineParams) error {
	_, err := q.db.Exec(ctx, revokeUnapprovedMachine, arg.Column1, arg.Column2)
	return err
}

const setMachineAutomaticUpdates = `-- name: SetMachineAutomaticUpdates :one
UPDATE machines
SET automatic_updates = $3
WHERE id = $1::uuid AND user_id = $2::uuid AND approved_at IS NOT NULL AND revoked_at IS NULL
RETURNING id, user_id, display_name, credential_hash, approved_at, revoked_at, created_at, last_seen_at, automatic_updates, daemon_version
`

type SetMachineAutomaticUpdatesParams struct {
	Column1          pgtype.UUID `json:"column_1"`
	Column2          pgtype.UUID `json:"column_2"`
	AutomaticUpdates bool        `json:"automatic_updates"`
}

func (q *Queries) SetMachineAutomaticUpdates(ctx context.Context, arg SetMachineAutomaticUpdatesParams) (Machine, error) {
	row := q.db.QueryRow(ctx, setMachineAutomaticUpdates, arg.Column1, arg.Column2, arg.AutomaticUpdates)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CredentialHash,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AutomaticUpdates,
		&i.DaemonVersion,
	)
	return i, err
}

const touchMachine = `-- name: TouchMachine :exec
UPDATE machines SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchMachine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchMachine, id)
	return err
}
