// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessRequest struct {
	Email            string             `json:"email"`
	FirstRequestedAt pgtype.Timestamptz `json:"first_requested_at"`
	LastRequestedAt  pgtype.Timestamptz `json:"last_requested_at"`
	TimesRequested   int32              `json:"times_requested"`
}

type ContextDocument struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Hash           []byte      `json:"hash"`
	Kind           string      `json:"kind"`
	Body           string      `json:"body"`
}

type Conversation struct {
	ID          pgtype.UUID        `json:"id"`
	Title       *string            `json:"title"`
	Folder      string             `json:"folder"`
	Provider    string             `json:"provider"`
	ModelID     string             `json:"model_id"`
	ModelLabel  string             `json:"model_label"`
	Archived    bool               `json:"archived"`
	SpendTicks  int64              `json:"spend_ticks"`
	Tokens      int64              `json:"tokens"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserID      pgtype.UUID        `json:"user_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

type ConversationFile struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	EntryID        pgtype.UUID        `json:"entry_id"`
	Origin         string             `json:"origin"`
	Name           string             `json:"name"`
	MediaType      string             `json:"media_type"`
	Size           int64              `json:"size"`
	Sha256         string             `json:"sha256"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ConversationFileContent struct {
	FileID  pgtype.UUID `json:"file_id"`
	Content []byte      `json:"content"`
}

type EmailLink struct {
	TokenHash    []byte             `json:"token_hash"`
	Kind         string             `json:"kind"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	SupersededAt pgtype.Timestamptz `json:"superseded_at"`
}

type Entry struct {
	ID               pgtype.UUID        `json:"id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	Seq              int32              `json:"seq"`
	Role             string             `json:"role"`
	Body             string             `json:"body"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Provider         *string            `json:"provider"`
	ModelID          *string            `json:"model_id"`
	ModelLabel       *string            `json:"model_label"`
	Tokens           *int64             `json:"tokens"`
	SpendTicks       *int64             `json:"spend_ticks"`
	Failure          *string            `json:"failure"`
	MessagesReplayed *int32             `json:"messages_replayed"`
	Stopped          bool               `json:"stopped"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

type Exchange struct {
	EntryID         pgtype.UUID        `json:"entry_id"`
	ConversationID  pgtype.UUID        `json:"conversation_id"`
	Program         string             `json:"program"`
	Args            []string           `json:"args"`
	Cwd             string             `json:"cwd"`
	ResumeSessionID string             `json:"resume_session_id"`
	Prompt          string             `json:"prompt"`
	Stdin           string             `json:"stdin"`
	Launched        bool               `json:"launched"`
	DroppedLines    int64              `json:"dropped_lines"`
	DroppedBytes    int64              `json:"dropped_bytes"`
	LineCount       int32              `json:"line_count"`
	ByteCount       int64              `json:"byte_count"`
	LastAtMs        int64              `json:"last_at_ms"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ContextRead     bool               `json:"context_read"`
	ContextFrom     string             `json:"context_from"`
	ContextError    string             `json:"context_error"`
}

type ExchangeContext struct {
	EntryID        pgtype.UUID `json:"entry_id"`
	Ord            int32       `json:"ord"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Hash           []byte      `json:"hash"`
}

type ExchangeLine struct {
	EntryID pgtype.UUID `json:"entry_id"`
	Seq     int32       `json:"seq"`
	AtMs    int64       `json:"at_ms"`
	Stream  string      `json:"stream"`
	Body    string      `json:"body"`
}

type Machine struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DisplayName      string             `json:"display_name"`
	CredentialHash   []byte             `json:"credential_hash"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	AutomaticUpdates bool               `json:"automatic_updates"`
	DaemonVersion    *string            `json:"daemon_version"`
}

type MachinePairing struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	Status    string             `json:"status"`
	MachineID pgtype.UUID        `json:"machine_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
}

type ProviderSession struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Provider       string             `json:"provider"`
	SessionID      *string            `json:"session_id"`
	SeenSeq        int32              `json:"seen_seq"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UserAgent  string             `json:"user_agent"`
	Ip         string             `json:"ip"`
	UserID     pgtype.UUID        `json:"user_id"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AppearanceMode    string             `json:"appearance_mode"`
	AppearanceSurface string             `json:"appearance_surface"`
	AppearanceAccent  string             `json:"appearance_accent"`
	DisplayName       string             `json:"display_name"`
	Bio               string             `json:"bio"`
}

type UserAvatar struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ContentType string             `json:"content_type"`
	Bytes       []byte             `json:"bytes"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMachine struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	MachineID   pgtype.UUID        `json:"machine_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
