// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProviderSession = `-- name: GetProviderSession :one
SELECT conversation_id, provider, session_id, seen_seq, updated_at FROM provider_sessions WHERE conversation_id = $1 AND provider = $2
`

type GetProviderSessionParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Provider       string      `json:"provider"`
}

func (q *Queries) GetProviderSession(ctx context.Context, arg GetProviderSessionParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, getProviderSession, arg.ConversationID, arg.Provider)
	var i ProviderSession
	err := row.Scan(
		&i.ConversationID,
		&i.Provider,
		&i.SessionID,
		&i.SeenSeq,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderSessions = `-- name: ListProviderSessions :many
SELECT conversation_id, provider, session_id, seen_seq, updated_at FROM provider_sessions WHERE conversation_id = $1
`

func (q *Queries) ListProviderSessions(ctx context.Context, conversationID pgtype.UUID) ([]ProviderSession, error) {
	rows, err := q.db.Query(ctx, listProviderSessions, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderSession{}
	for rows.Next() {
		var i ProviderSession
		if err := rows.Scan(
			&i.ConversationID,
			&i.Provider,
			&i.SessionID,
			&i.SeenSeq,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderSeen = `-- name: UpsertProviderSeen :one
INSERT INTO provider_sessions (conversation_id, provider, seen_seq, session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (conversation_id, provider) DO UPDATE
SET seen_seq   = GREATEST(provider_sessions.seen_seq, EXCLUDED.seen_seq),
    session_id = COALESCE(EXCLUDED.session_id, provider_sessions.session_id),
    updated_at = now()
RETURNING conversation_id, provider, session_id, seen_seq, updated_at
`

type UpsertProviderSeenParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Provider       string      `json:"provider"`
	SeenSeq        int32       `json:"seen_seq"`
	SessionID      *string     `json:"session_id"`
}

// seen_seq only ever moves forward. A replay that lands out of order must not
// rewind it, or the next switch would re-send entries the provider already has.
func (q *Queries) UpsertProviderSeen(ctx context.Context, arg UpsertProviderSeenParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, upsertProviderSeen,
		arg.ConversationID,
		arg.Provider,
		arg.SeenSeq,
		arg.SessionID,
	)
	var i ProviderSession
	err := row.Scan(
		&i.ConversationID,
		&i.Provider,
		&i.SessionID,
		&i.SeenSeq,
		&i.UpdatedAt,
	)
	return i, err
}
