// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchConversations = `-- name: SearchConversations :many
SELECT
    c.id, c.title, c.folder, c.provider, c.model_id, c.model_label, c.archived, c.spend_ticks, c.tokens, c.created_at, c.updated_at, c.user_id, c.workspace_id,
    (
        SELECT e.body
        FROM entries e
        WHERE e.conversation_id = c.id
          AND e.role <> 'replay'
          AND e.body ILIKE '%' || $1::text || '%'
        ORDER BY e.seq
        LIMIT 1
    ) AS excerpt
FROM conversations c
WHERE c.workspace_id = $2
  AND EXISTS (
        SELECT 1 FROM workspace_members m
        WHERE m.workspace_id = c.workspace_id AND m.user_id = $3
  )
  AND (
        c.title ILIKE '%' || $1::text || '%'
     OR c.folder ILIKE '%' || $1::text || '%'
     OR EXISTS (
            SELECT 1
            FROM entries e2
            WHERE e2.conversation_id = c.id
              AND e2.role <> 'replay'
              AND e2.body ILIKE '%' || $1::text || '%'
        )
  )
ORDER BY c.updated_at DESC
`

type SearchConversationsParams struct {
	Q           string      `json:"q"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

type SearchConversationsRow struct {
	Conversation Conversation `json:"conversation"`
	Excerpt      string       `json:"excerpt"`
}

// Titles alone would miss the conversations that most need finding. A name is
// derived from the first message or typed by hand, so it describes where a
// conversation started and never where it ended up — and the thing you go
// looking for is usually what was said in the middle of it.
//
// The excerpt is the first matching message body, so a hit in a long transcript
// is explicable rather than mysterious. A title match returns none — the reason
// for that hit is already on screen.
//
// One workspace's conversations, and only for an account that is in it. Both
// filters wrap the whole match, so no OR branch can reach past either of them.
// Searching across every workspace at once would undo the separation the
// workspaces are for (D-050): a search in Personal must not surface work.
func (q *Queries) SearchConversations(ctx context.Context, arg SearchConversationsParams) ([]SearchConversationsRow, error) {
	rows, err := q.db.Query(ctx, searchConversations, arg.Q, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchConversationsRow{}
	for rows.Next() {
		var i SearchConversationsRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.Title,
			&i.Conversation.Folder,
			&i.Conversation.Provider,
			&i.Conversation.ModelID,
			&i.Conversation.ModelLabel,
			&i.Conversation.Archived,
			&i.Conversation.SpendTicks,
			&i.Conversation.Tokens,
			&i.Conversation.CreatedAt,
			&i.Conversation.UpdatedAt,
			&i.Conversation.UserID,
			&i.Conversation.WorkspaceID,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
