// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING token_hash, created_at, last_seen_at, expires_at, user_agent, ip, user_id
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent string             `json:"user_agent"`
	Ip        string             `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.UserID,
	)
	return i, err
}

const deleteDeadSessions = `-- name: DeleteDeadSessions :execrows
DELETE FROM sessions
WHERE expires_at < now() OR last_seen_at < $1
`

func (q *Queries) DeleteDeadSessions(ctx context.Context, idleSince pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadSessions, idleSince)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1
`

// Signing out everywhere. Used by "sign out everywhere" and by a password
// change, which ends every session INCLUDING the caller's: the reason to change
// a password is usually that somebody else may hold a session, and a session
// token is a something they could hold. The caller then issues itself a fresh
// one, so the owner stays signed in and the old token is dead.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT token_hash, created_at, last_seen_at, expires_at, user_agent, ip, user_id FROM sessions WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.UserAgent,
			&i.Ip,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET last_seen_at = now()
WHERE token_hash = $1
  AND expires_at > now()
  AND last_seen_at > $2
RETURNING token_hash, created_at, last_seen_at, expires_at, user_agent, ip, user_id
`

type TouchSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	IdleSince pgtype.Timestamptz `json:"idle_since"`
}

// Validating and touching a session are ONE statement on purpose. Read-then-
// write would leave a window where a session deleted in between is still
// accepted, and the whole point of storing sessions in rows is that deleting one
// takes effect immediately.
//
// Two expiries, both checked here: expires_at is how old a session may get,
// idle_since is how long it may go unused. A row that fails either is simply not
// returned, and the caller sees the same "not a valid session" as for a token
// that never existed.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.TokenHash, arg.IdleSince)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.UserID,
	)
	return i, err
}
