// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// How many accounts exist. Tests use it to assert a flow created exactly the
// accounts it should have.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

// users_email_key is the constraint that can refuse this: the same address
// twice. Any number of people may have accounts (migrations/00009); who may
// create one is decided before this runs, by the invitation list.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEveryAccessRequest = `-- name: DeleteEveryAccessRequest :exec
DELETE FROM access_requests
`

func (q *Queries) DeleteEveryAccessRequest(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryAccessRequest)
	return err
}

const deleteEveryConversation = `-- name: DeleteEveryConversation :exec
DELETE FROM conversations
`

func (q *Queries) DeleteEveryConversation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryConversation)
	return err
}

const deleteEveryEmailLink = `-- name: DeleteEveryEmailLink :exec

DELETE FROM email_links
`

// Tests only, all six. A suite needs a way back to "nobody has an account",
// and conversations reference users WITHOUT a cascade (D-009), so their rows go
// first. Sessions go with their users by ON DELETE CASCADE. Links and access
// requests are keyed by address rather than by account, so they are emptied
// explicitly — a request left from an earlier run would stop the next run's
// first request from being the first.
func (q *Queries) DeleteEveryEmailLink(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryEmailLink)
	return err
}

const deleteEveryEntry = `-- name: DeleteEveryEntry :exec
DELETE FROM entries
`

func (q *Queries) DeleteEveryEntry(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryEntry)
	return err
}

const deleteEveryProviderSession = `-- name: DeleteEveryProviderSession :exec
DELETE FROM provider_sessions
`

func (q *Queries) DeleteEveryProviderSession(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEveryProviderSession)
	return err
}

const deleteEveryUser = `-- name: DeleteEveryUser :execrows
DELETE FROM users
`

func (q *Queries) DeleteEveryUser(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEveryUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForChange = `-- name: GetUserByEmailForChange :one
SELECT id, email, password_hash, created_at, updated_at FROM users WHERE email = $1 FOR UPDATE
`

// Resetting a forgotten password: the same lock as GetUserForChange, found by
// the address the reset link was sent to rather than by a session.
func (q *Queries) GetUserByEmailForChange(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForChange, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForSignIn = `-- name: GetUserByEmailForSignIn :one
SELECT id, email, password_hash, created_at, updated_at FROM users WHERE email = $1 FOR SHARE
`

// Signing in, holding the row against a password change.
//
// FOR SHARE rather than a plain read, and it matters. Verifying a password
// takes ~50ms of argon2, and without a lock a sign-in can read the OLD hash,
// spend that time, and insert its session AFTER a password change has deleted
// every session — so the password the owner just revoked still produces a
// working login. FOR SHARE does not block other sign-ins (they share it); it
// blocks only GetUserForChange below, which is exactly the conflict.
func (q *Queries) GetUserByEmailForSignIn(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForSignIn, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForChange = `-- name: GetUserForChange :one
SELECT id, email, password_hash, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

// Changing the password, excluding everything else on this row.
//
// FOR UPDATE waits for any sign-in holding FOR SHARE to finish, so the sessions
// this change is about to delete include that one. It also serialises two
// simultaneous changes, which would otherwise both verify against the same old
// hash and one would silently overwrite the other.
func (q *Queries) GetUserForChange(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForChange, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserEmail = `-- name: SetUserEmail :one
UPDATE users SET email = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, created_at, updated_at
`

type SetUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) SetUserEmail(ctx context.Context, arg SetUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, created_at, updated_at
`

type SetUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
