// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name) VALUES ($1) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT w.id, w.name, w.created_at, w.updated_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE w.id = $1 AND m.user_id = $2
`

type GetWorkspaceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetWorkspaceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (GetWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getWorkspace, arg.ID, arg.UserID)
	var i GetWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many

SELECT w.id, w.name, w.created_at, w.updated_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.name, w.created_at
`

type ListWorkspacesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

// A workspace is a separate area of work inside an account, and an account
// reaches one by being a member of it (docs/Decisions.md D-050). Every
// statement here joins that membership, for the same reason every conversation
// statement does: an id is not permission.
// The switcher's list, and the answer to "does this account have a workspace at
// all" that first-run setup asks.
//
// Ordered by name rather than by when it was made, because this is a list
// somebody reads to find one of two or three things, and creation order is not
// how anyone remembers them.
func (q *Queries) ListWorkspaces(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesRow{}
	for rows.Next() {
		var i ListWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWorkspace = `-- name: RenameWorkspace :one
UPDATE workspaces SET name = $1, updated_at = now()
WHERE id = $2
  AND EXISTS (
      SELECT 1 FROM workspace_members m
      WHERE m.workspace_id = workspaces.id AND m.user_id = $3 AND m.role = 'owner'
  )
RETURNING id, name, created_at, updated_at
`

type RenameWorkspaceParams struct {
	Name   string      `json:"name"`
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Renaming is the only edit a workspace has. What it holds is edited through
// the things it holds.
func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, renameWorkspace, arg.Name, arg.ID, arg.UserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
