"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, Check, ChevronRight, Download, MonitorSmartphone, PlugZap, Plus, RefreshCw, Wifi, WifiOff } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import type { Machine } from "@/lib/chat-types";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { ProductSidebar } from "@/components/product-sidebar";

const machineKey = ["machines"] as const;
type PairingStage = "waiting" | "unanswered" | "approval";
type PairingState = { id: string; uri: string; stage: PairingStage };
function status(machine: Machine) { return machine.online ? "Online" : "Offline"; }

function PairingPanel({ state, retry, approve, approving, notNow, declining }: { state: PairingState; retry: () => void; approve: () => void; approving: boolean; notNow: () => void; declining: boolean }) {
  if (state.stage === "approval") return <section className="mt-5 border px-4 py-4"><h2 className="text-sm font-medium">Approve this computer?</h2><p className="mt-1 text-sm text-muted-foreground">It will be able to run coding agents for your account.</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={approve} disabled={approving || declining}>{approving ? "Connecting…" : "Approve computer"}</Button><Button size="sm" variant="outline" onClick={notNow} disabled={approving || declining}>Not now</Button></div></section>;
  const unanswered = state.stage === "unanswered";
  return <section className="mt-5 border px-4 py-4"><div className="flex items-start gap-3"><Wifi className="mt-0.5 size-4 shrink-0"/><div><h2 className="text-sm font-medium">{unanswered ? "This computer has not answered yet" : "Looking for this computer"}</h2><p className="mt-1 text-sm text-muted-foreground">{unanswered ? "It may still be starting. Retry, or install the Windows component if it is not on this computer yet." : "Approve the browser prompt to open sparstrowgen on this computer."}</p></div></div>{unanswered && <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={retry}><RefreshCw/>Retry</Button><Button size="sm" variant="outline" render={<Link href="/install"/>}><Download/>Install component</Button></div>}</section>;
}

export function MachinesSurface() {
  const queryClient = useQueryClient();
  const list = useQuery({ queryKey: machineKey, queryFn: api.machines });
  const create = useMutation({ mutationFn: api.startPairing });
  const approve = useMutation({ mutationFn: api.approvePairing });
  const decline = useMutation({ mutationFn: api.declinePairing });
  const [pairing, setPairing] = useState<PairingState | null>(null);
  const launch = (uri: string) => { window.location.assign(uri); };
  async function begin() { try { const next = await create.mutateAsync(); setPairing({ id: next.pairing.id, uri: next.launchUri, stage: "waiting" }); launch(next.launchUri); } catch (error) { toast.error("Could not start pairing", { description: (error as Error).message }); } }
  async function connect() { if (!pairing) return; try { await approve.mutateAsync(pairing.id); setPairing(null); await queryClient.invalidateQueries({ queryKey: machineKey }); toast.success("Computer connected"); } catch (error) { toast.error("Could not connect this computer", { description: (error as Error).message }); } }
  async function notNow() { if (!pairing) return; try { await decline.mutateAsync(pairing.id); } catch (error) { toast.error("Could not dismiss this computer", { description: (error as Error).message }); return; } setPairing(null); await queryClient.invalidateQueries({ queryKey: machineKey }); }
  useEffect(() => { if (!pairing || pairing.stage === "approval") return; const timeout = window.setTimeout(() => setPairing((current) => current?.stage === "waiting" ? { ...current, stage: "unanswered" } : current), 8_000); const poll = window.setInterval(() => void (async () => { try { const current = await api.pairing(pairing.id); if (current.status === "claimed") setPairing((prior) => prior ? { ...prior, stage: "approval" } : prior); else if (current.status === "approved") { setPairing(null); await queryClient.invalidateQueries({ queryKey: machineKey }); toast.success("This computer is already connected"); } else if (current.status === "rejected") setPairing(null); } catch (error) { setPairing(null); toast.error("Pairing stopped", { description: (error as Error).message }); } })(), 1_500); return () => { window.clearTimeout(timeout); window.clearInterval(poll); }; }, [pairing, queryClient]);
  return <SidebarProvider className="h-full"><ProductSidebar current="machines"/><SidebarInset className="min-w-0 rounded-none"><main className="mx-auto w-full max-w-5xl px-6 py-8"><header className="flex items-center justify-between gap-4 border-b pb-5"><div><h1 className="text-lg font-medium tracking-tight">Machines</h1><p className="mt-1 text-sm text-muted-foreground">Computers that can run work for you.</p></div><Button onClick={() => void begin()} disabled={create.isPending}><Plus/>Add computer</Button></header>{pairing && <PairingPanel state={pairing} retry={() => launch(pairing.uri)} approve={() => void connect()} approving={approve.isPending} notNow={() => void notNow()} declining={decline.isPending}/>}<MachineList list={list.data} pending={list.isPending} failed={list.isError} error={list.error} retry={() => void list.refetch()} begin={() => void begin()}/></main></SidebarInset></SidebarProvider>;
}

function MachineList({ list, pending, failed, error, retry, begin }: { list?: Machine[]; pending: boolean; failed: boolean; error: unknown; retry: () => void; begin: () => void }) {
  if (pending) return <div className="mt-6 space-y-3">{[1, 2].map((i) => <Skeleton key={i} className="h-16 w-full"/>)}</div>;
  if (failed) return <Empty className="mt-14 border"><EmptyHeader><EmptyMedia variant="icon"><PlugZap/></EmptyMedia><EmptyTitle>Machines could not be loaded</EmptyTitle><EmptyDescription>{(error as Error).message}</EmptyDescription></EmptyHeader><EmptyContent><Button variant="outline" onClick={retry}>Try again</Button></EmptyContent></Empty>;
  if (!list?.length) return <Empty className="mt-14"><EmptyHeader><EmptyMedia variant="icon"><MonitorSmartphone/></EmptyMedia><EmptyTitle>No computers connected</EmptyTitle><EmptyDescription>Pair the computer where your coding agents are installed. You can add another later.</EmptyDescription></EmptyHeader><EmptyContent><Button onClick={begin}><Plus/>Add computer</Button></EmptyContent></Empty>;
  return <div className="mt-6 divide-y rounded-lg border">{list.map((machine) => <Link key={machine.id} href={`/machines/${machine.id}`} className="flex items-center gap-4 px-4 py-4 transition-colors hover:bg-muted/50"><MonitorSmartphone className="size-5 text-muted-foreground"/><div className="min-w-0 flex-1"><div className="font-medium">{machine.name}</div><div className="mt-0.5 text-xs text-muted-foreground">{machine.providers.length} provider{machine.providers.length === 1 ? "" : "s"} available</div></div><div className="flex items-center gap-2 text-sm"><span className="sr-only">{status(machine)}</span>{machine.online ? <Wifi className="size-4 text-success"/> : <WifiOff className="size-4 text-muted-foreground"/>}<span className={machine.online ? "text-success-text" : undefined}>{status(machine)}</span></div><ChevronRight className="size-4 text-muted-foreground"/></Link>)}</div>;
}

export function MachineProfile({ id }: { id: string }) {
  const router = useRouter(); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ["machines", id], queryFn: () => api.machine(id) }); const remove = useMutation({ mutationFn: api.disconnectMachine, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: machineKey }); router.push("/machines"); } });
  return <SidebarProvider className="h-full"><ProductSidebar current="machines"/><SidebarInset className="min-w-0 rounded-none"><main className="mx-auto w-full max-w-3xl px-6 py-8">{query.isPending ? <div className="space-y-4"><Skeleton className="h-8 w-52"/><Skeleton className="h-32 w-full"/></div> : query.isError ? <Empty><EmptyHeader><EmptyMedia variant="icon"><PlugZap/></EmptyMedia><EmptyTitle>Machine unavailable</EmptyTitle><EmptyDescription>{(query.error as Error).message}</EmptyDescription></EmptyHeader><EmptyContent><Button render={<Link href="/machines"/>} variant="outline">Back to machines</Button></EmptyContent></Empty> : query.data && <><Link href="/machines" className="text-sm text-muted-foreground hover:text-foreground">Machines</Link><header className="mt-6 flex items-start justify-between gap-4 border-b pb-5"><div className="flex items-center gap-3"><MonitorSmartphone className="size-6"/><div><h1 className="text-lg font-medium">{query.data.name}</h1><p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground">{query.data.online ? <Wifi className="size-3.5 text-success"/> : <WifiOff className="size-3.5"/>}<span className={query.data.online ? "text-success-text" : undefined}>{status(query.data)}</span></p></div></div><AlertDialog><AlertDialogTrigger render={<Button variant="destructive" size="sm" disabled={remove.isPending}/>}>Disconnect</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Disconnect this computer?</AlertDialogTitle><AlertDialogDescription>It will no longer be able to run new work until it is paired again.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => void remove.mutate(query.data.id)}>Disconnect</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></header><section className="mt-7"><h2 className="text-sm font-medium">Agent providers</h2><p className="mt-1 text-sm text-muted-foreground">Providers this computer can make available to new work.</p><div className="mt-4 divide-y border-y">{query.data.providers.length ? query.data.providers.map((provider) => <div className="flex items-center justify-between py-3" key={provider.id}><span className="font-medium">{provider.label}</span><span className="flex items-center gap-1.5 text-sm text-muted-foreground">{provider.availability === "available" ? <Check className="size-3.5 text-success" aria-hidden="true"/> : <AlertCircle className="size-3.5" aria-hidden="true"/>}{provider.availability === "available" ? "Available" : provider.unavailableReason ?? "Unavailable"}</span></div>) : <p className="py-5 text-sm text-muted-foreground">Waiting for this computer to connect and report its providers.</p>}</div></section></>}</main></SidebarInset></SidebarProvider>;
}
