"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronRight, MonitorSmartphone, PlugZap, Plus, Wifi, WifiOff } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import type { Machine } from "@/lib/chat-types";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { ProductSidebar } from "@/components/product-sidebar";

const machineKey = ["machines"] as const;
function status(m: Machine) { return m.online ? "Online" : m.approved ? "Offline" : "Waiting for approval"; }

export function MachinesSurface() {
 const qc=useQueryClient(); const list=useQuery({queryKey:machineKey,queryFn:api.machines}); const pair=useMutation({mutationFn:api.startPairing});
 const [pairing,setPairing]=useState<{id:string;uri:string}|null>(null);
 const requestPairing=async()=>{try{const next=await pair.mutateAsync();setPairing({id:next.pairing.id,uri:next.launchUri});window.location.assign(next.launchUri)}catch(e){toast.error("Could not start pairing",{description:(e as Error).message})}};
 useEffect(()=>{if(!pairing)return;const tick=async()=>{try{const p=await api.pairing(pairing.id);if(p.status==="claimed"){await api.approvePairing(p.id);setPairing(null);await qc.invalidateQueries({queryKey:machineKey});toast.success("Computer connected")} }catch(e){toast.error("Pairing stopped",{description:(e as Error).message});setPairing(null)}};const id=setInterval(()=>void tick(),1500);return()=>clearInterval(id)},[pairing,qc]);
 return <SidebarProvider className="h-full"><ProductSidebar current="machines"/><SidebarInset className="min-w-0 rounded-none"><main className="mx-auto w-full max-w-5xl px-6 py-8"><header className="flex items-center justify-between gap-4 border-b pb-5"><div><h1 className="text-lg font-medium tracking-tight">Machines</h1><p className="mt-1 text-sm text-muted-foreground">Computers that can run work for you.</p></div><Button onClick={()=>void requestPairing()} disabled={pair.isPending}><Plus/>Add computer</Button></header>
 {pairing&&<div className="mt-5 flex items-center gap-3 border rounded-lg px-4 py-3 text-sm"><Wifi className="size-4"/><span>Waiting for this computer to answer the pairing request.</span><span className="ml-auto text-muted-foreground">Expires soon</span></div>}
 {list.isPending?<div className="mt-6 space-y-3">{[1,2].map(i=><Skeleton key={i} className="h-16 w-full"/>)}</div>:list.isError?<Empty className="mt-14 border"><EmptyHeader><EmptyMedia variant="icon"><PlugZap/></EmptyMedia><EmptyTitle>Machines could not be loaded</EmptyTitle><EmptyDescription>{(list.error as Error).message}</EmptyDescription></EmptyHeader><EmptyContent><Button variant="outline" onClick={()=>void list.refetch()}>Try again</Button></EmptyContent></Empty>:!list.data?.length?<Empty className="mt-14"><EmptyHeader><EmptyMedia variant="icon"><MonitorSmartphone/></EmptyMedia><EmptyTitle>No computers connected</EmptyTitle><EmptyDescription>Pair the computer where your coding agents are installed. You can add another later.</EmptyDescription></EmptyHeader><EmptyContent><Button onClick={()=>void requestPairing()}><Plus/>Add computer</Button></EmptyContent></Empty>:<div className="mt-6 divide-y rounded-lg border">{list.data.map(m=><Link key={m.id} href={`/machines/${m.id}`} className="flex items-center gap-4 px-4 py-4 transition-colors hover:bg-muted/50"><MonitorSmartphone className="size-5 text-muted-foreground"/><div className="min-w-0 flex-1"><div className="font-medium">{m.name}</div><div className="mt-0.5 text-xs text-muted-foreground">{m.providers.length} provider{m.providers.length===1?"":"s"} available</div></div><div className="flex items-center gap-2 text-sm"><span className="sr-only">{status(m)}</span>{m.online?<Wifi className="size-4"/>:<WifiOff className="size-4 text-muted-foreground"/>}<span>{status(m)}</span></div><ChevronRight className="size-4 text-muted-foreground"/></Link>)}</div>}</main></SidebarInset></SidebarProvider>
}

export function MachineProfile({id}:{id:string}) { const router=useRouter(); const qc=useQueryClient();const q=useQuery({queryKey:["machines",id],queryFn:()=>api.machine(id)});const remove=useMutation({mutationFn:api.disconnectMachine,onSuccess:()=>{void qc.invalidateQueries({queryKey:machineKey});router.push("/machines")}});return <SidebarProvider className="h-full"><ProductSidebar current="machines"/><SidebarInset className="min-w-0 rounded-none"><main className="mx-auto w-full max-w-3xl px-6 py-8">{q.isPending?<div className="space-y-4"><Skeleton className="h-8 w-52"/><Skeleton className="h-32 w-full"/></div>:q.isError?<Empty><EmptyHeader><EmptyMedia variant="icon"><PlugZap/></EmptyMedia><EmptyTitle>Machine unavailable</EmptyTitle><EmptyDescription>{(q.error as Error).message}</EmptyDescription></EmptyHeader><EmptyContent><Button render={<Link href="/machines"/>} variant="outline">Back to machines</Button></EmptyContent></Empty>:q.data&&<><Link href="/machines" className="text-sm text-muted-foreground hover:text-foreground">Machines</Link><header className="mt-6 flex items-start justify-between gap-4 border-b pb-5"><div className="flex items-center gap-3"><MonitorSmartphone className="size-6"/><div><h1 className="text-lg font-medium">{q.data.name}</h1><p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground">{q.data.online?<Wifi className="size-3.5"/>:<WifiOff className="size-3.5"/>}{status(q.data)}</p></div></div><AlertDialog><AlertDialogTrigger render={<Button variant="destructive" size="sm" disabled={remove.isPending}/>}>Disconnect</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Disconnect this computer?</AlertDialogTitle><AlertDialogDescription>It will no longer be able to run new work until it is paired again.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>void remove.mutate(q.data.id)}>Disconnect</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></header><section className="mt-7"><h2 className="text-sm font-medium">Agent providers</h2><p className="mt-1 text-sm text-muted-foreground">Providers this computer can make available to new work.</p><div className="mt-4 divide-y border-y">{q.data.providers.length?q.data.providers.map(p=><div className="flex items-center justify-between py-3" key={p.id}><span className="font-medium">{p.label}</span><span className="flex items-center gap-1.5 text-sm text-muted-foreground"><Check className="size-3.5"/>{p.availability==="available"?"Available":p.unavailableReason??"Unavailable"}</span></div>):<p className="py-5 text-sm text-muted-foreground">{q.data.approved?"Waiting for this computer to connect and report its providers.":"Approve this computer to finish pairing."}</p>}</div></section></>}</main></SidebarInset></SidebarProvider> }
