import { SupabaseClient } from "@supabase/supabase-js";

export async function getActiveWorkspaceId(
  supabase: SupabaseClient,
  searchParams?: URLSearchParams
): Promise<{ workspaceId?: string; error?: string; status?: number; workspaces?: any[] }> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { error: "Unauthorized", status: 401 };
  }

  const { data: memberships, error: memError } = await supabase
    .from("workspace_members")
    .select("workspace_id, workspaces(id, name)");

  if (memError) {
    return { error: "Database error", status: 500 };
  }

  if (!memberships || memberships.length === 0) {
    try {
      const workspaceId = await bootstrapWorkspace(supabase, user);
      return { workspaceId };
    } catch (err: any) {
      // If it failed due to unique constraint, try to read again
      if (err.code === "23505" || err.message?.includes("duplicate key")) {
        const { data: retryMemberships } = await supabase
          .from("workspace_members")
          .select("workspace_id")
          .limit(1);
        if (retryMemberships && retryMemberships.length > 0) {
          return { workspaceId: retryMemberships[0].workspace_id };
        }
      }
      return { error: "Failed to bootstrap workspace", status: 500 };
    }
  }

  if (memberships.length === 1) {
    return { workspaceId: memberships[0].workspace_id };
  }

  const requestedWorkspaceId = searchParams?.get("workspaceId");
  if (requestedWorkspaceId) {
    const isMember = memberships.some((m) => m.workspace_id === requestedWorkspaceId);
    if (isMember) {
      return { workspaceId: requestedWorkspaceId };
    }
  }

  const workspaces = memberships.map((m) => m.workspaces).filter(Boolean);
  return { error: "Multiple workspaces found", status: 400, workspaces };
}

async function bootstrapWorkspace(supabase: SupabaseClient, user: any): Promise<string> {
  // Every id column in the control plane is `text primary key` with no database
  // default — ids are generated by whoever writes the row, matching how the
  // local daemon does it. Generating the workspace id here also means we never
  // need `.select()` on the insert: `insert ... returning` is evaluated against
  // the SELECT policy, and at this moment the caller is not yet a member of the
  // workspace being created, so RETURNING comes back empty and supabase-js
  // reports it as a row-level-security violation.
  const workspaceId = crypto.randomUUID();

  // 1. users — `name` is NOT NULL with no default.
  const { error: userError } = await supabase.from("users").insert({
    id: user.id,
    email: user.email,
    name:
      user.user_metadata?.full_name ??
      user.user_metadata?.name ??
      user.email?.split("@")[0] ??
      "User",
  });

  if (userError && userError.code !== "23505") {
    throw userError;
  }

  // 2. workspaces — `id` and `slug` are both NOT NULL, and slug is UNIQUE, so
  // it is derived from the id rather than from the (non-unique) display name.
  const { error: wsError } = await supabase.from("workspaces").insert({
    id: workspaceId,
    name: "Personal Workspace",
    slug: `personal-${workspaceId.slice(0, 8)}`,
    owner_id: user.id,
  });

  if (wsError) {
    throw wsError;
  }

  // 3. workspace_members — permitted here because the caller owns the
  // workspace inserted above; see policies/003_bootstrap_fix.sql.
  const { error: wmError } = await supabase.from("workspace_members").insert({
    id: crypto.randomUUID(),
    workspace_id: workspaceId,
    user_id: user.id,
    role: "owner",
  });

  if (wmError) {
    throw wmError;
  }

  return workspaceId;
}
